In [1]:
#pip install requests beautifulsoup4 pandas lxml html5lib 
#pip install --upgrade certifi

import pandas as pd
import numpy as np

def clean_brvm_dataframe(df):
    """
    Nettoie automatiquement toutes les colonnes d'un DataFrame de la BRVM.
    Gère les espaces, les espaces insécables, les virgules et les pourcentages.
    """
    # 1. Nettoyer les noms de colonnes
    df.columns = [str(c).strip() for c in df.columns]
    
    for col in df.columns:
        # On ignore les colonnes qui sont déjà nativement reconnues comme numériques
        if pd.api.types.is_numeric_dtype(df[col]):
            continue
            
        # Conversion en texte pour manipulation
        col_str = df[col].astype(str)
        
        # 2. Détection de la présence de pourcentages (dans le nom ou les valeurs)
        is_pct = '%' in col or col_str.str.contains('%', na=False).any()
        
        # 3. Étape clé : Regex pour supprimer TOUS les espaces (classiques et insécables)
        cleaned = col_str.str.replace(r'[\s\xa0]+', '', regex=True)
        # Remplacement de la virgule francophone par le point informatique
        cleaned = cleaned.str.replace(',', '.', regex=False)
        
        if is_pct:
            # On retire le symbole %
            cleaned = cleaned.str.replace('%', '', regex=False)
            # Conversion en numérique et division par 100 
            df[col] = pd.to_numeric(cleaned, errors='coerce') / 100
        else:
            # 4. Pour les autres colonnes : Tentative de conversion numérique
            temp_numeric = pd.to_numeric(cleaned, errors='coerce')
            
            # Sécurité : vérifier que ce n'est pas une colonne de texte (ex: "Nom" ou "Symbole")
            # On vérifie si la conversion a créé des NaN inutiles.
            original_empty = cleaned.isin(['nan', 'None', '', 'NaN']).sum()
            new_nan = temp_numeric.isna().sum()
            
            # Si on n'a pas détruit de texte (le nombre de NaN est resté le même), 
            # c'est que la colonne était bien composée uniquement de chiffres.
            if new_nan == original_empty and temp_numeric.notna().sum() > 0:
                # Pandas gérera automatiquement int (entier) ou float (décimal)
                df[col] = temp_numeric
                
    return df




import pandas as pd
import requests
import urllib3
from io import StringIO

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

URL = "https://www.brvm.org/fr/cours-actions/0"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
}


print("--- Extraction en cours ---")
try:
    response = requests.get(URL, headers=HEADERS, verify=False, timeout=15)
    response.raise_for_status()
    
    # Extraction brute
    toutes_les_tables = pd.read_html(StringIO(response.text))
    
    if len(toutes_les_tables) >= 4:
        # Assignation ET Nettoyage immédiat
        df_top      = clean_brvm_dataframe(toutes_les_tables[0].copy())
        df_flop     = clean_brvm_dataframe(toutes_les_tables[1].copy())
        df_activite = clean_brvm_dataframe(toutes_les_tables[2].copy())
        df_actions  = clean_brvm_dataframe(toutes_les_tables[3].copy())

        print("✅ Tables extraites et nettoyées avec succès !")

except Exception as e:
    print(f"❌ Erreur : {e}")





URL = "https://www.brvm.org/fr/volumes/0"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
}


print("--- Extraction en cours ---")
try:
    response = requests.get(URL, headers=HEADERS, verify=False, timeout=15)
    response.raise_for_status()
    
    # Extraction brute
    toutes_les_tables = pd.read_html(StringIO(response.text))

except Exception as e:
    print(f"❌ Erreur : {e}")

volume=clean_brvm_dataframe(toutes_les_tables[3].copy())



actions=df_actions.merge(volume, left_on=["Symbole","Nom"],right_on=["Code obligation","Nom"], how="left")[['Symbole', 'Nom', 'Volume', 'Cours veille (FCFA)',
       'Cours Ouverture (FCFA)', 'Cours Clôture (FCFA)', 'Variation (%)', 'Valeur échangée','PER', 'Pourcentage de la valeur globale échangée']]

actions['PER']=actions['PER'].apply(lambda x: int(x)/100 if x.isdigit() else x)

Pour la suite du developpement, 
je dois recuperer la date et l'heure de l'actualisaéton à chaque fois
cette information sera donc sauvegardé dans la table des actions fusionnées
l'idée derrière cette modification c'est d'incrementer les données sur les données precedemment sauvegarder à chaque fois.

Ensuite une reflexion doit etre mené pour la sauvegarde... est ce que on passera par sql ou une sauvegarde classique dans un csv qui sera à chaque fois incrementer( voir limite potentielle de cette methode)

Une fois la partie data achevée, nous pourrons nous focaliser sur la recuperation de l'historique sur le github de koffi(https://github.com/Fredysessie/brvm-data-public/blob/main/data/LNBB/LNBB.daily.csv)

Une fois cette etape achevée, nous pourrons alors penser à la modelisation des données hitoire d'obtenir les indicateurs clés de notre analyse sur la brvm (Reflexion à mener sur les indicateurs et leurs pertinence)

In [2]:
import pandas as pd
import requests
import urllib3
from io import StringIO
from typing import List, Optional
import re
from datetime import datetime

# Désactivation de l'avertissement SSL (si nécessaire pour BRVM)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def clean_brvm_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Nettoie automatiquement toutes les colonnes d'un DataFrame de la BRVM.
    Gère les espaces, les espaces insécables, les virgules et les pourcentages.
    """
    df = df.copy() # Évite les warnings SettingWithCopy
    df.columns = df.columns.str.strip()
    
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            continue
            
        col_str = df[col].astype(str)
        is_pct = '%' in col or col_str.str.contains('%', na=False).any()
        
        # Chaînage optimisé : Suppression des espaces (\s et \xa0) et remplacement de la virgule
        cleaned = col_str.str.replace(r'[\s\xa0]+', '', regex=True).str.replace(',', '.', regex=False)
        
        if is_pct:
            cleaned = cleaned.str.replace('%', '', regex=False)
            df[col] = pd.to_numeric(cleaned, errors='coerce') / 100
        else:
            temp_numeric = pd.to_numeric(cleaned, errors='coerce')
            
            # Vérification de sécurité (heuristique des NaN)
            original_empty = cleaned.isin(['nan', 'None', '', 'NaN']).sum()
            new_nan = temp_numeric.isna().sum()
            
            if new_nan == original_empty and temp_numeric.notna().sum() > 0:
                df[col] = temp_numeric
                
    return df



def fetch_brvm_tables(url: str, session: requests.Session) -> List[pd.DataFrame]:
    """
    Récupère de manière sécurisée les tables HTML d'une URL donnée.
    """
    print(f"--- Extraction en cours : {url} ---")
    headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}
    
    try:
        response = session.get(url, headers=headers, verify=False, timeout=15)
        response.raise_for_status()
        return pd.read_html(StringIO(response.text))
    except requests.exceptions.RequestException as e:
        print(f"❌ Erreur réseau lors de l'accès à {url} : {e}")
        return []
    except ValueError:
        print(f"❌ Aucune table HTML trouvée sur {url}.")
        return []
    

    
    
def refresh_date(url: str, session: requests.Session):
    """
    Récupère la date de dernière mise à jour sur le site de la BRVM 
    et la retourne sous forme de timestamp UNIX.
    """
    mois_fr = {
        'janvier': 1, 'février': 2, 'mars': 3, 'avril': 4, 'mai': 5, 'juin': 6,
        'juillet': 7, 'août': 8, 'septembre': 9, 'octobre': 10, 'novembre': 11, 'décembre': 12
    }
    
    try:
        # 1. On exécute la requête pour obtenir le HTML
        # On met un entête classique pour éviter d'être bloqué
        headers = {"User-Agent": "Mozilla/5.0"}
        response = session.get(url, headers=headers, verify=False, timeout=15)
        response.raise_for_status()

        # 2. On cherche le texte situé juste après "Dernière mise à jour :"
        match_maj = re.search(r'Dernière mise à jour\s*:\s*([^\n<]+)', response.text)

        if match_maj:
            date_actualisation = match_maj.group(1).strip() 
            
            # 3. On applique la regex de conversion sur la date trouvée
            match_dt = re.search(r'(\d+)\s+([a-zA-Zéû]+)[,\s]+(\d{4})\s*-\s+(\d{2}):(\d{2})', date_actualisation.lower())
            
            if match_dt:
                dt = datetime(
                    int(match_dt.group(3)),              # Année
                    mois_fr.get(match_dt.group(2), 1),   # Mois
                    int(match_dt.group(1)),              # Jour
                    int(match_dt.group(4)),              # Heure
                    int(match_dt.group(5))               # Minute
                )
                
                print(f"✅ Date refresh : {dt}")
                return dt

    except Exception as e:
        print(f"❌ Erreur lors de l'extraction de la date : {e}")

    # Retourne None si la date n'est pas trouvée ou si la requête échoue
    return None



def main():
    # 1. Utilisation d'une session pour accélérer les requêtes multiples sur le même domaine
    with requests.Session() as session:
        url_actions = "https://www.brvm.org/fr/cours-actions/0"
        tables_actions = fetch_brvm_tables(url_actions, session)
        
        url_volumes = "https://www.brvm.org/fr/volumes/0"
        tables_volumes = fetch_brvm_tables(url_volumes, session)

        date_refresh = refresh_date(url_actions, session)

    # 2. Vérification de l'intégrité des données extraites
    if len(tables_actions) < 4 or len(tables_volumes) < 4:
        print("❌ Extraction incomplète. Arrêt du script.")
        return None

    # 3. Nettoyage ciblé uniquement sur les tables nécessaires
    print("--- Nettoyage des données ---")
    df_actions = clean_brvm_dataframe(tables_actions[3])
    volume = clean_brvm_dataframe(tables_volumes[3])

    # 4. Fusion des DataFrames
    print("--- Fusion des données ---")
    actions = df_actions.merge(
        volume, 
        left_on=["Symbole", "Nom"], 
        right_on=["Code obligation", "Nom"], 
        how="left"
    )

    # Filtrage sécurisé des colonnes (évite une KeyError si le site BRVM change une colonne)
    colonnes_voulues = [
        'Symbole', 'Nom', 'Volume', 'Cours veille (FCFA)', 'Cours Ouverture (FCFA)', 
        'Cours Clôture (FCFA)', 'Variation (%)', 'Valeur échangée', 'PER', 
        'Pourcentage de la valeur globale échangée'
    ]
    colonnes_existantes = [col for col in colonnes_voulues if col in actions.columns]
    actions = actions[colonnes_existantes]

    # 5. Optimisation : Remplacement du lambda par une opération vectorisée Pandas
    if 'PER' in actions.columns:
        actions['PER']=actions['PER'].apply(lambda x: int(x)/100 if x.isdigit() else x)

    print("✅ Traitement terminé avec succès !")

    #Intrsion date
    actions['Date Refresh'] = date_refresh
    return actions

# --- Exécution ---
if __name__ == "__main__":
    df_final = main()
    # Si tu veux afficher un aperçu :
    # if df_final is not None:
    #     print(df_final.head())

--- Extraction en cours : https://www.brvm.org/fr/cours-actions/0 ---
--- Extraction en cours : https://www.brvm.org/fr/volumes/0 ---
✅ Date refresh : 2026-05-11 13:04:00
--- Nettoyage des données ---
--- Fusion des données ---
✅ Traitement terminé avec succès !

In [3]:
df_final

,Symbole,Nom,Volume,Cours veille (FCFA),Cours Ouverture (FCFA),Cours Clôture (FCFA),Variation (%),Valeur échangée,PER,Pourcentage de la valeur globale échangée,Date Refresh
0,ABJC,SERVAIR ABIDJAN COTE D'IVOIRE,7762,2955,2995,2960,-50,22924200,24.23,249,2026-05-11 13:04:00
1,BICB,BANQUE INTERNATIONALE POUR L’INDUSTRIE ET LE C...,1541,5225,5165,5200,-48,7980845,9.95,87,2026-05-11 13:04:00
2,BICC,BICI COTE D'IVOIRE,539,26000,26095,26095,37,14044240,11.87,153,2026-05-11 13:04:00
3,BNBC,BERNABE COTE D'IVOIRE,845,1390,1345,1390,692,1121935,412.55,12,2026-05-11 13:04:00
4,BOAB,BANK OF AFRICA BENIN,11991,9400,9400,9390,-11,112860910,18.96,1227,2026-05-11 13:04:00
5,BOABF,BANK OF AFRICA BURKINA FASO,3372,5400,5400,5410,19,18217515,12.34,198,2026-05-11 13:04:00
6,BOAC,BANK OF AFRICA COTE D'IVOIRE,3457,8695,8700,8600,-121,29774835,10.85,324,2026-05-11 13:04:00
7,BOAM,BANK OF AFRICA MALI,4011,4700,4700,4680,-43,18810730,11.64,205,2026-05-11 13:04:00
8,BOAN,BANK OF AFRICA NIGER,7281,3485,3480,3480,-14,25324145,177.12,275,2026-05-11 13:04:00
9,BOAS,BANK OF AFRICA SENEGAL,6130,7390,7400,7425,47,45536170,12.15,495,2026-05-11 13:04:00
10,CABC,SICABLE COTE D'IVOIRE,1828,3400,3500,3400,-286,6307195,13.98,69,2026-05-11 13:04:00
11,CBIBF,CORIS BANK INTERNATIONAL BURKINA FASO,1345,16800,16800,16800,0,22660070,8.21,246,2026-05-11 13:04:00
12,CFAC,CFAO MOTORS COTE D'IVOIRE,1143,1385,1385,1360,-181,1572800,53.52,17,2026-05-11 13:04:00
13,CIEC,CIE COTE D'IVOIRE,2358,3120,3330,3120,-631,7586140,17.3,82,2026-05-11 13:04:00
14,ECOC,ECOBANK COTE D'IVOIRE,1969,16300,17000,16200,-357,32109300,14.14,349,2026-05-11 13:04:00
15,ETIT,Ecobank Transnational Incorporated TOGO,505678,29,28,29,-333,14400289,1.52,157,2026-05-11 13:04:00
16,FTSC,FILTISAC COTE D'IVOIRE,1270,2220,2240,2235,68,2837910,1.68,31,2026-05-11 13:04:00
17,LNBB,LOTERIE NATIONALE DU BENIN,905,3845,3845,3860,39,3484895,16.64,38,2026-05-11 13:04:00
18,NEIC,NEI-CEDA COTE D'IVOIRE,2226,1795,1745,1795,287,3896380,11.25,42,2026-05-11 13:04:00
19,NSBC,NSIA BANQUE COTE D'IVOIRE,2469,14010,13990,13850,-114,34313405,9.09,373,2026-05-11 13:04:00
20,NTLC,NESTLE COTE D'IVOIRE,440,11650,11700,11640,-9,5079105,13.95,55,2026-05-11 13:04:00
21,ONTBF,ONATEL BURKINA FASO,1729,2700,2760,2700,-217,4757890,12.65,52,2026-05-11 13:04:00
22,ORAC,ORANGE COTE D'IVOIRE,391,14920,14920,14950,20,5855920,13.4,64,2026-05-11 13:04:00
23,ORGT,ORAGROUP TOGO,21367,2700,2740,2740,745,58400485,8.66,635,2026-05-11 13:04:00
24,PALC,PALM COTE D'IVOIRE,545,7800,7800,7685,-147,4202425,7.78,46,2026-05-11 13:04:00
25,PRSC,TRACTAFRIC MOTORS COTE D'IVOIRE,748,3695,3690,3695,0,2761805,15.98,30,2026-05-11 13:04:00
26,SAFC,SAFCA COTE D'IVOIRE,1760,3485,3500,3485,-43,6092940,40.37,66,2026-05-11 13:04:00
27,SCRC,SUCRIVOIRE COTE D'IVOIRE,7185,2260,2425,2265,-582,16882805,-,184,2026-05-11 13:04:00
28,SDCC,SODE COTE D'IVOIRE,498,9095,9095,9095,0,4529845,13.92,49,2026-05-11 13:04:00
29,SDSC,AFRICA GLOBAL LOGISTICS COTE D'IVOIRE,8703,1710,1750,1710,-201,14877285,4.42,162,2026-05-11 13:04:00
30,SEMC,EVIOSYS PACKAGING SIEM COTE D'IVOIRE,3425,1530,1530,1520,-33,5199750,38.08,57,2026-05-11 13:04:00
31,SGBC,SOCIETE GENERALE COTE D'IVOIRE,837,34500,34750,34795,86,29055190,10.59,316,2026-05-11 13:04:00
32,SHEC,VIVO ENERGY COTE D'IVOIRE,8639,1985,1950,1950,26,17051440,20.75,185,2026-05-11 13:04:00
33,SIBC,SOCIETE IVOIRIENNE DE BANQUE COTE D'IVOIRE,4031,7095,7100,7100,7,28611795,12.76,311,2026-05-11 13:04:00
34,SICC,SICOR COTE D'IVOIRE,39,4400,4280,4400,256,167400,137.18,2,2026-05-11 13:04:00
35,SIVC,ERIUM COTE D’IVOIRE,7793,2845,2800,2860,53,21884590,65.92,238,2026-05-11 13:04:00
36,SLBC,SOLIBRA COTE D'IVOIRE,64,37500,38000,37600,27,2428100,28.75,26,2026-05-11 13:04:00
37,SMBC,SMB COTE D'IVOIRE,947,11995,11995,12200,171,11388425,7.15,124,2026-05-11 13:04:00
38,SNTS,SONATEL SENEGAL,2842,28900,28900,28900,0,82104980,6.99,893,2026-05-11 13:04:00
39,SOGC,SOGB COTE D'IVOIRE,1192,7390,7390,7390,0,8803385,12.78,96,2026-05-11 13:04:00
40,SPHC,SAPH COTE D'IVOIRE,2773,7050,7050,7050,0,19441480,7.22,211,2026-05-11 13:04:00
41,STAC,SETAO COTE D'IVOIRE,4554,2600,2695,2600,-226,11850255,-,129,2026-05-11 13:04:00
42,STBC,SITAB COTE D'IVOIRE,3813,21500,21500,21300,-93,81458690,10.68,886,2026-05-11 13:04:00
43,TTLC,TOTALENERGIES MARKETING COTE D'IVOIRE,9616,2750,2750,2750,0,27095910,19.05,295,2026-05-11 13:04:00
44,TTLS,TOTALENERGIES MARKETING SENEGAL,2614,2950,2910,2900,-169,7604645,14.18,83,2026-05-11 13:04:00
45,UNLC,UNILEVER COTE D'IVOIRE,7,60200,56000,59900,696,416400,863.36,5,2026-05-11 13:04:00
46,UNXC,UNIWAX COTE D'IVOIRE,8729,1845,1805,1840,194,15939510,-,173,2026-05-11 13:04:00

In [4]:
import pandas as pd
import requests
import urllib3
from io import StringIO
from typing import List, Tuple, Optional
import re
from datetime import datetime

# Désactivation de l'avertissement SSL
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Constante globale pour éviter la répétition
HEADERS = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}

def clean_brvm_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Nettoie automatiquement toutes les colonnes d'un DataFrame de la BRVM.
    Gère les espaces, les espaces insécables, les virgules et les pourcentages.
    """
    df = df.copy() 
    df.columns = df.columns.str.strip()
    
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            continue
            
        col_str = df[col].astype(str)
        is_pct = '%' in col or col_str.str.contains('%', na=False).any()
        
        cleaned = col_str.str.replace(r'[\s\xa0]+', '', regex=True).str.replace(',', '.', regex=False)
        
        if is_pct:
            cleaned = cleaned.str.replace('%', '', regex=False)
            df[col] = pd.to_numeric(cleaned, errors='coerce') / 100
        else:
            temp_numeric = pd.to_numeric(cleaned, errors='coerce')
            
            original_empty = cleaned.isin(['nan', 'None', '', 'NaN']).sum()
            new_nan = temp_numeric.isna().sum()
            
            if new_nan == original_empty and temp_numeric.notna().sum() > 0:
                df[col] = temp_numeric
                
    return df


def fetch_brvm_data(url: str, session: requests.Session) -> Tuple[List[pd.DataFrame], str]:
    """
    Récupère de manière sécurisée les tables HTML et le texte brut d'une URL donnée.
    """
    print(f"--- Extraction en cours : {url} ---")
    
    try:
        response = session.get(url, headers=HEADERS, verify=False, timeout=15)
        response.raise_for_status()
        html_text = response.text
        # On retourne les tables ET le HTML pour éviter de refaire une requête plus tard
        return pd.read_html(StringIO(html_text)), html_text
    except Exception as e:
        print(f"❌ Erreur réseau lors de l'accès à {url} : {e}")
        return [], ""


def refresh_date(html_text: str) -> Optional[datetime]:
    """
    Extrait la date de dernière mise à jour directement depuis une chaîne HTML.
    Aucune requête réseau n'est effectuée ici.
    """
    if not html_text:
        return None
        
    mois_fr = {
        'janvier': 1, 'février': 2, 'mars': 3, 'avril': 4, 'mai': 5, 'juin': 6,
        'juillet': 7, 'août': 8, 'septembre': 9, 'octobre': 10, 'novembre': 11, 'décembre': 12
    }
    
    try:
        match_maj = re.search(r'Dernière mise à jour\s*:\s*([^\n<]+)', html_text)

        if match_maj:
            date_actualisation = match_maj.group(1).strip() 
            match_dt = re.search(r'(\d+)\s+([a-zA-Zéû]+)[,\s]+(\d{4})\s*-\s+(\d{2}):(\d{2})', date_actualisation.lower())
            
            if match_dt:
                dt = datetime(
                    int(match_dt.group(3)),
                    mois_fr.get(match_dt.group(2), 1),
                    int(match_dt.group(1)),
                    int(match_dt.group(4)),
                    int(match_dt.group(5))
                )
                print(f"✅ Date refresh trouvée : {dt}")
                return dt

    except Exception as e:
        print(f"❌ Erreur lors de l'extraction de la date : {e}")

    return None


def main():
    # 1. Extraction (Session unique maintenue ouverte)
    with requests.Session() as session:
        url_actions = "https://www.brvm.org/fr/cours-actions/0"
        # On récupère les tables ET le code HTML de la page actions
        tables_actions, html_actions = fetch_brvm_data(url_actions, session)
        
        url_volumes = "https://www.brvm.org/fr/volumes/0"
        # Le HTML des volumes n'est pas nécessaire, on l'ignore avec "_"
        tables_volumes, _ = fetch_brvm_data(url_volumes, session)

        # 2. Récupération de la date SANS nouvelle requête (on utilise le HTML déjà téléchargé)
        date_refresh = refresh_date(html_actions)

    # 3. Vérification de l'intégrité
    if len(tables_actions) < 4 or len(tables_volumes) < 4:
        print("❌ Extraction incomplète. Arrêt du script.")
        return None

    # 4. Nettoyage
    print("--- Nettoyage des données ---")
    df_actions = clean_brvm_dataframe(tables_actions[3])
    volume = clean_brvm_dataframe(tables_volumes[3])

    # 5. Fusion
    print("--- Fusion des données ---")
    actions = df_actions.merge(
        volume, 
        left_on=["Symbole", "Nom"], 
        right_on=["Code obligation", "Nom"], 
        how="left"
    )

    # 6. Filtrage sécurisé
    colonnes_voulues = [
        'Symbole', 'Nom', 'Volume', 'Cours veille (FCFA)', 'Cours Ouverture (FCFA)', 
        'Cours Clôture (FCFA)', 'Variation (%)', 'Valeur échangée', 'PER', 
        'Pourcentage de la valeur globale échangée'
    ]
    colonnes_existantes = [col for col in colonnes_voulues if col in actions.columns]
    actions = actions[colonnes_existantes]

    # 7. process PER
    if 'PER' in actions.columns:
        actions['PER']=actions['PER'].apply(lambda x: int(x)/100 if x.isdigit() else x)

    # 8. Insertion de la date
    actions['Date Refresh'] = date_refresh
    
    print("✅ Traitement terminé avec succès !")
    return actions


if __name__ == "__main__":
    df_final = main()

--- Extraction en cours : https://www.brvm.org/fr/cours-actions/0 ---
--- Extraction en cours : https://www.brvm.org/fr/volumes/0 ---
✅ Date refresh trouvée : 2026-05-12 19:15:00
--- Nettoyage des données ---
--- Fusion des données ---
✅ Traitement terminé avec succès !

In [5]:
df_final

,Symbole,Nom,Volume,Cours veille (FCFA),Cours Ouverture (FCFA),Cours Clôture (FCFA),Variation (%),Valeur échangée,PER,Pourcentage de la valeur globale échangée,Date Refresh
0,ABJC,SERVAIR ABIDJAN COTE D'IVOIRE,7588,2985,2995,2980,-17,22618910,24.47,154,2026-05-12 19:15:00
1,BICB,BANQUE INTERNATIONALE POUR L’INDUSTRIE ET LE C...,1578,5170,5200,5200,58,8201500,9.84,56,2026-05-12 19:15:00
2,BICC,BICI COTE D'IVOIRE,561,26200,26200,26300,38,14757815,11.96,100,2026-05-12 19:15:00
3,BNBC,BERNABE COTE D'IVOIRE,7896,1490,1415,1495,717,11638415,442.23,79,2026-05-12 19:15:00
4,BOAB,BANK OF AFRICA BENIN,11117,9405,9405,9420,16,104616915,18.97,712,2026-05-12 19:15:00
5,BOABF,BANK OF AFRICA BURKINA FASO,5219,5410,5400,5410,0,28188865,12.36,192,2026-05-12 19:15:00
6,BOAC,BANK OF AFRICA COTE D'IVOIRE,7396,8650,8655,8585,-75,63520075,10.8,432,2026-05-12 19:15:00
7,BOAM,BANK OF AFRICA MALI,4155,4685,4695,4680,-11,19491500,11.61,133,2026-05-12 19:15:00
8,BOAN,BANK OF AFRICA NIGER,5724,3450,3445,3440,-29,19710885,175.34,134,2026-05-12 19:15:00
9,BOAS,BANK OF AFRICA SENEGAL,8857,7450,7460,7500,67,66160735,12.24,450,2026-05-12 19:15:00
10,CABC,SICABLE COTE D'IVOIRE,514,3400,3370,3400,-286,1771050,13.98,12,2026-05-12 19:15:00
11,CBIBF,CORIS BANK INTERNATIONAL BURKINA FASO,1535,17495,17000,17400,357,26165565,8.55,178,2026-05-12 19:15:00
12,CFAC,CFAO MOTORS COTE D'IVOIRE,1999,1380,1380,1380,0,2753120,53.33,19,2026-05-12 19:15:00
13,CIEC,CIE COTE D'IVOIRE,4424,3295,3295,3295,297,14584590,18.27,99,2026-05-12 19:15:00
14,ECOC,ECOBANK COTE D'IVOIRE,4831,16205,16200,16200,0,78174125,14.05,532,2026-05-12 19:15:00
15,ETIT,Ecobank Transnational Incorporated TOGO,331249,30,30,30,0,9701545,1.57,66,2026-05-12 19:15:00
16,FTSC,FILTISAC COTE D'IVOIRE,1798,2200,2200,2240,182,3980815,1.67,27,2026-05-12 19:15:00
17,LNBB,LOTERIE NATIONALE DU BENIN,2217,3865,3865,3865,0,8569055,16.72,58,2026-05-12 19:15:00
18,NEIC,NEI-CEDA COTE D'IVOIRE,12358,1890,1840,1890,216,22963125,11.85,156,2026-05-12 19:15:00
19,NSBC,NSIA BANQUE COTE D'IVOIRE,1964,13850,13850,13810,-29,27128620,8.99,185,2026-05-12 19:15:00
20,NTLC,NESTLE COTE D'IVOIRE,470,11700,11700,11700,493,5475850,14.01,37,2026-05-12 19:15:00
21,ONTBF,ONATEL BURKINA FASO,592,2700,2700,2680,-74,1594670,12.65,11,2026-05-12 19:15:00
22,ORAC,ORANGE COTE D'IVOIRE,492,15100,15100,15050,-33,7436600,13.56,51,2026-05-12 19:15:00
23,ORGT,ORAGROUP TOGO,10458,2750,2940,2740,0,28961200,8.82,197,2026-05-12 19:15:00
24,PALC,PALM COTE D'IVOIRE,1639,7800,7700,7850,64,12644770,7.78,86,2026-05-12 19:15:00
25,PRSC,TRACTAFRIC MOTORS COTE D'IVOIRE,850,3650,3650,3690,110,3109455,15.79,21,2026-05-12 19:15:00
26,SAFC,SAFCA COTE D'IVOIRE,33876,3745,3745,3745,746,126830280,43.38,863,2026-05-12 19:15:00
27,SCRC,SUCRIVOIRE COTE D'IVOIRE,8131,2260,2255,2285,111,18361815,-,125,2026-05-12 19:15:00
28,SDCC,SODE COTE D'IVOIRE,1414,9395,9100,9395,330,12951190,14.38,88,2026-05-12 19:15:00
29,SDSC,AFRICA GLOBAL LOGISTICS COTE D'IVOIRE,12445,1745,1710,1745,265,21392370,4.51,146,2026-05-12 19:15:00
30,SEMC,EVIOSYS PACKAGING SIEM COTE D'IVOIRE,4159,1505,1505,1500,-33,6238675,37.46,42,2026-05-12 19:15:00
31,SGBC,SOCIETE GENERALE COTE D'IVOIRE,1717,34800,34800,34990,55,59927065,10.68,408,2026-05-12 19:15:00
32,SHEC,VIVO ENERGY COTE D'IVOIRE,3609,1945,2000,1940,-300,7102370,20.33,48,2026-05-12 19:15:00
33,SIBC,SOCIETE IVOIRIENNE DE BANQUE COTE D'IVOIRE,4674,7290,7100,7295,217,33459370,13.11,228,2026-05-12 19:15:00
34,SICC,SICOR COTE D'IVOIRE,26,4400,4390,4390,-23,114140,137.18,1,2026-05-12 19:15:00
35,SIVC,ERIUM COTE D’IVOIRE,4743,2855,2865,2860,18,13646730,66.15,93,2026-05-12 19:15:00
36,SLBC,SOLIBRA COTE D'IVOIRE,453,37900,37900,37500,-106,17068290,29.05,116,2026-05-12 19:15:00
37,SMBC,SMB COTE D'IVOIRE,375,12690,12100,12685,483,4621520,7.57,31,2026-05-12 19:15:00
38,SNTS,SONATEL SENEGAL,12483,29000,29000,28910,-31,361564440,7.01,2460,2026-05-12 19:15:00
39,SOGC,SOGB COTE D'IVOIRE,2237,7400,7100,7400,7,16116655,12.8,110,2026-05-12 19:15:00
40,SPHC,SAPH COTE D'IVOIRE,838,7000,7000,6995,-7,5839650,7.16,40,2026-05-12 19:15:00
41,STAC,SETAO COTE D'IVOIRE,2364,2600,2515,2600,338,5969630,-,41,2026-05-12 19:15:00
42,STBC,SITAB COTE D'IVOIRE,3004,21290,21290,21050,-113,63549580,10.57,432,2026-05-12 19:15:00
43,TTLC,TOTALENERGIES MARKETING COTE D'IVOIRE,19254,3060,2850,3060,737,56524595,21.2,385,2026-05-12 19:15:00
44,TTLS,TOTALENERGIES MARKETING SENEGAL,2044,2820,2850,2845,-190,5800435,13.55,39,2026-05-12 19:15:00
45,UNLC,UNILEVER COTE D'IVOIRE,21,56100,59890,56100,-634,1227370,804.56,8,2026-05-12 19:15:00
46,UNXC,UNIWAX COTE D'IVOIRE,9600,1835,1835,1825,-54,17612910,-,120,2026-05-12 19:15:00

In [ ]:
import os
from supabase import create_client, Client
# ... (Tout ton code de nettoyage précédent reste identique) ...

    # 8. Insertion de la date
    actions['Date Refresh'] = date_refresh
    
    print("✅ Traitement terminé avec succès !")

    # --- NOUVEAU : PREPARATION POUR SUPABASE ---
    print("--- Envoi des données vers Supabase ---")
    
    # 1. Renommer les colonnes pour qu'elles correspondent exactement à la table SQL
    colonnes_mapping = {
        'Symbole': 'symbole',
        'Nom': 'nom',
        'Volume': 'volume',
        'Cours veille (FCFA)': 'cours_veille',
        'Cours Ouverture (FCFA)': 'cours_ouverture',
        'Cours Clôture (FCFA)': 'cours_cloture',
        'Variation (%)': 'variation',
        'Valeur échangée': 'valeur_echangee',
        'PER': 'per',
        'Pourcentage de la valeur globale échangée': 'pourcentage_valeur',
        'Date Refresh': 'date_refresh'
    }
    actions = actions.rename(columns=colonnes_mapping)

    # 2. Convertir la date datetime en format texte ISO (Requis par les bases de données)
    # On vérifie que la date existe bien
    if date_refresh:
        actions['date_refresh'] = actions['date_refresh'].dt.isoformat()
    
    # 3. Remplacer les éventuels NaN par None (JSON/Supabase n'aime pas les NaN de Pandas)
    actions = actions.where(pd.notnull(actions), None)

    # 4. Convertir le DataFrame en liste de dictionnaires
    data_to_insert = actions.to_dict(orient='records')

    # 5. Connexion à Supabase
    # REMPLACE CES VALEURS PAR TES CLES SUPABASE
    SUPABASE_URL = "https://TON_PROJET.supabase.co"
    SUPABASE_KEY = "TA_CLE_ANON_PUBLIQUE"
    
    try:
        supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
        
        # On fait un "upsert" : si la donnée existe déjà (même symbole, même date), il l'ignore
        response = supabase.table("historique_cours").upsert(data_to_insert).execute()
        print(f"✅ {len(data_to_insert)} lignes envoyées à Supabase avec succès !")
    except Exception as e:
        print(f"❌ Erreur lors de l'envoi à Supabase : {e}")

    return actions

if __name__ == "__main__":
    df_final = main()

In [3]:
pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv
  WARNING: The script dotenv is installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed python-dotenv-1.2.2

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install dash

Collecting dash
  Downloading dash-4.1.0-py3-none-any.whl.metadata (11 kB)
Collecting Flask<3.2,>=1.0.4 (from dash)
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting Werkzeug<3.2 (from dash)
  Downloading werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Collecting plotly>=5.0.0 (from dash)
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Collecting importlib-metadata (from dash)
  Downloading importlib_metadata-9.0.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: typing_extensions>=4.1.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from dash) (4.15.0)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from dash) (2.33.1)
Collecting retrying (from dash)
  Downloading retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: nest-asyncio in /Users/aemmanuelhounkponou/Library/Python/3.13/lib/python/site-packages (from dash) (1.6.0)
Collecting setuptools (from dash)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting blinker>=1.9.0 (from Flask<3.2,>=1.0.4->dash)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: click>=8.1.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (8.3.3)
Collecting itsdangerous>=2.2.0 (from Flask<3.2,>=1.0.4->dash)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting jinja2>=3.1.2 (from Flask<3.2,>=1.0.4->dash)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting markupsafe>=2.1.1 (from Flask<3.2,>=1.0.4->dash)
  Downloading markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting narwhals>=1.15.1 (from plotly>=5.0.0->dash)
  Downloading narwhals-2.21.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: packaging in /Users/aemmanuelhounkponou/Library/Python/3.13/lib/python/site-packages (from plotly>=5.0.0->dash) (26.2)
Collecting zipp>=3.20 (from importlib-metadata->dash)
  Downloading zipp-3.23.1-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->dash) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->dash) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->dash) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->dash) (2026.4.22)
Downloading dash-4.1.0-py3-none-any.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 723.0 kB/s  0:00:10 eta 0:00:01
Downloading flask-3.1.3-py3-none-any.whl (103 kB)
Downloading werkzeug-3.1.8-py3-none-any.whl (226 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl (12 kB)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 2.7 MB/s  0:00:03 eta 0:00:01
Downloading narwhals-2.21.0-py3-none-any.whl (451 kB)
Downloading importlib_metadata-9.0.0-py3-none-any.whl (27 kB)
Downloading zipp-3.23.1-py3-none-any.whl (10 kB)
Downloading retrying-1.4.2-py3-none-any.whl (10 kB)
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 4.4 MB/s  0:00:00 eta 0:00:01
Installing collected packages: zipp, setuptools, retrying, narwhals, markupsafe, itsdangerous, blinker, Werkzeug, plotly, jinja2, importlib-metadata, Flask, dash
   ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━  8/13 [plotly]s]s]  WARNING: The script plotly_get_chrome is installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━  9/13 [jinja2]  WARNING: The script flask is installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━ 12/13 [dash]  WARNING: The scripts dash-generate-components, dash-update-components, plotly and renderer are installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [dash]
Successfully installed Flask-3.1.3 Werkzeug-3.1.8 blinker-1.9.0 dash-4.1.0 importlib-metadata-9.0.0 itsdangerous-2.2.0 jinja2-3.1.6 markupsafe-3.0.3 narwhals-2.21.0 plotly-6.7.0 retrying-1.4.2 setuptools-82.0.1 zipp-3.23.1

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install plotly

Requirement already satisfied: plotly in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from plotly) (2.21.0)
Requirement already satisfied: packaging in /Users/aemmanuelhounkponou/Library/Python/3.13/lib/python/site-packages (from plotly) (26.2)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:



# --- 2. INITIALISATION DE L'APPLICATION DASH ---
app = Dash(__name__)
app.title = "BRVM Analytics Pro"

# --- 3. MISE EN PAGE (HTML structuré en Python) ---
app.layout = html.Div(style={'fontFamily': 'Arial, sans-serif', 'padding': '20px', 'backgroundColor': '#f8f9fa'}, children=[
    
    # En-tête
    html.H1("📈 Terminal BRVM Analytics", style={'textAlign': 'center', 'color': '#2c3e50'}),
    html.P("Plateforme d'Intelligence Financière", style={'textAlign': 'center', 'color': '#7f8c8d'}),
    
    # Contrôles (Menu déroulant)
    html.Div(style={'width': '300px', 'margin': '0 auto', 'paddingBottom': '30px'}, children=[
        html.Label("Sélectionnez une action :", style={'fontWeight': 'bold'}),
        dcc.Dropdown(
            id='dropdown-action',
            options=[{'label': sym, 'value': sym} for sym in symboles_disponibles],
            value=symboles_disponibles[0] if symboles_disponibles else None,
            clearable=False
        )
    ]),

    # Cartes KPI (Chiffres clés)
    html.Div(style={'display': 'flex', 'justifyContent': 'space-around', 'marginBottom': '30px'}, children=[
        html.Div(style={'backgroundColor': 'white', 'padding': '20px', 'borderRadius': '10px', 'boxShadow': '0 4px 6px rgba(0,0,0,0.1)', 'textAlign': 'center', 'width': '20%'}, children=[
            html.H4("Cours Actuel", style={'margin': '0', 'color': '#7f8c8d'}),
            html.H2(id='kpi-cours', style={'margin': '10px 0', 'color': '#2c3e50'})
        ]),
        html.Div(style={'backgroundColor': 'white', 'padding': '20px', 'borderRadius': '10px', 'boxShadow': '0 4px 6px rgba(0,0,0,0.1)', 'textAlign': 'center', 'width': '20%'}, children=[
            html.H4("Volume", style={'margin': '0', 'color': '#7f8c8d'}),
            html.H2(id='kpi-volume', style={'margin': '10px 0', 'color': '#2c3e50'})
        ]),
        html.Div(style={'backgroundColor': 'white', 'padding': '20px', 'borderRadius': '10px', 'boxShadow': '0 4px 6px rgba(0,0,0,0.1)', 'textAlign': 'center', 'width': '20%'}, children=[
            html.H4("RSI (14j)", style={'margin': '0', 'color': '#7f8c8d'}),
            html.H2(id='kpi-rsi', style={'margin': '10px 0', 'color': '#2c3e50'})
        ]),
    ]),

    # Graphique Principal
    html.Div(style={'backgroundColor': 'white', 'padding': '20px', 'borderRadius': '10px', 'boxShadow': '0 4px 6px rgba(0,0,0,0.1)'}, children=[
        dcc.Graph(id='graphique-principal')
    ])
])

# --- 4. LOGIQUE D'INTERACTION (Les Callbacks) ---
@app.callback(
    [Output('kpi-cours', 'children'),
     Output('kpi-volume', 'children'),
     Output('kpi-rsi', 'children'),
     Output('graphique-principal', 'figure')],
    [Input('dropdown-action', 'value')]
)
def update_dashboard(symbole_choisi):
    if not symbole_choisi or df_brvm.empty:
        return "-", "-", "-", go.Figure()

    # 1. Filtrer et calculer
    df_action = df_brvm[df_brvm['symbole'] == symbole_choisi]
    df_action = calculate_technical_indicators(df_action)
    
    dernier_cours = df_action.iloc[0]

    # 2. Préparer les textes des KPI
    variation = dernier_cours['variation']
    var_text = f" ({variation*100:+.2f}%)" if pd.notnull(variation) else ""
    txt_cours = f"{dernier_cours['cours_cloture']} FCFA{var_text}"
    txt_volume = f"{dernier_cours['volume']:,.0f}".replace(",", " ")
    
    rsi_val = dernier_cours['RSI_14']
    txt_rsi = f"{rsi_val:.1f}" if pd.notnull(rsi_val) else "N/A"
    if pd.notnull(rsi_val):
        txt_rsi += " 🔴" if rsi_val > 70 else " 🟢" if rsi_val < 30 else " ⚪"

    # 3. Construire le graphique Plotly
    fig = go.Figure()
    
    # Prix
    fig.add_trace(go.Scatter(x=df_action['date_refresh'], y=df_action['cours_cloture'], 
                             mode='lines', name='Cours de Clôture', line=dict(color='#2980b9', width=2)))
    # SMA 20
    fig.add_trace(go.Scatter(x=df_action['date_refresh'], y=df_action['SMA_20'], 
                             mode='lines', name='SMA 20', line=dict(color='#f39c12', dash='dot')))
    # SMA 50
    fig.add_trace(go.Scatter(x=df_action['date_refresh'], y=df_action['SMA_50'], 
                             mode='lines', name='SMA 50', line=dict(color='#e74c3c', dash='dash')))

    fig.update_layout(
        title=f"Analyse Technique : {symbole_choisi}",
        xaxis_title="Date",
        yaxis_title="Prix (FCFA)",
        hovermode="x unified",
        plot_bgcolor='white',
        paper_bgcolor='white',
        margin=dict(l=40, r=20, t=40, b=40)
    )
    # Ajout d'une grille légère
    fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='#ecf0f1')
    fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='#ecf0f1')

    # Retourner les valeurs pour mettre à jour la page
    return txt_cours, txt_volume, txt_rsi, fig

In [1]:
import pandas as pd
import plotly.graph_objects as go
from dash import Dash, html, dcc, Input, Output
#import sys
#import os
#sys.path.append('/Users/aemmanuelhounkponou/Developer/Personal/Invest_brvm')
from database import get_supabase_client

# --- 1. FONCTIONS DATA & SCIENCE ---
def load_data():
    """Charge TOUTES les données depuis Supabase en contournant la limite de 1000 lignes."""
    supabase = get_supabase_client()
    all_data = []
    
    # vu que supabase autorise max 1000 par défaut
    page_size = 1000 
    offset = 0
    
    print("⏳ Téléchargement de l'historique en cours...")
    
    while True:
        # On demande les lignes de 'offset' à 'offset + 999'
        response = supabase.table("full_stock_history") \
            .select("*") \
            .range(offset, offset + page_size - 1) \
            .execute()
            
        data = response.data
        
        # S'il n'y a plus de données, on casse la boucle
        if not data:
            break
            
        all_data.extend(data)
        offset += page_size
        
        # Si on récupère moins de 1000 lignes, c'est qu'on a atteint la toute fin
        if len(data) < page_size:
            break

    print(f"✅ {len(all_data)} lignes téléchargées avec succès !")
    
    # On transforme le tout en DataFrame
    df = pd.DataFrame(all_data)
    if not df.empty:
        df['date'] = pd.to_datetime(df['date'])
        
    return df


def calculate_technical_indicators(df):
    """Calcule les indicateurs techniques pour chaque action séparément."""
    # 1. On trie par Action (symbole) PUIS par Date chronologique
    df = df.sort_values(by=['symbole', 'date'], ascending=[True, True]).copy()
    
    # 2. On calcule les moyennes mobiles PAR GROUPE (par action)
    df['SMA_20'] = df.groupby('symbole')['close'].transform(lambda x: x.rolling(window=20).mean())
    df['SMA_50'] = df.groupby('symbole')['close'].transform(lambda x: x.rolling(window=50).mean())
    
    # 3. On calcule le RSI PAR GROUPE
    delta = df.groupby('symbole')['close'].diff()
    gain = (delta.where(delta > 0, 0)).groupby(df['symbole']).transform(lambda x: x.rolling(window=14).mean())
    loss = (-delta.where(delta < 0, 0)).groupby(df['symbole']).transform(lambda x: x.rolling(window=14).mean())
    rs = gain / loss
    df['RSI_14'] = 100 - (100 / (1 + rs))
    
    # On remet du plus récent au plus ancien pour l'affichage
    return df.sort_values(by='date', ascending=False)

# Chargement initial des données
df_brvm = load_data()
df_brvm1 = calculate_technical_indicators(df_brvm)
symboles_disponibles = sorted(df_brvm1['symbole'].unique()) if not df_brvm1.empty else []
print(f"Symboles disponibles pour le dashboard : {symboles_disponibles[:5]}...")  # Affiche les 5 premiers symboles pour vérification

# --- 5. LANCEMENT DU SERVEUR ---
#if __name__ == '__main__':
#    app.run_server(debug=True)

⏳ Téléchargement de l'historique en cours...
✅ 154384 lignes téléchargées avec succès !
Symboles disponibles pour le dashboard : ['ABJC', 'BICB', 'BICC', 'BNBC', 'BOAB']...

In [11]:
df_brvm[df_brvm['symbole']=='ABJC']['date'].unique()

<DatetimeArray>
['2026-05-13 00:00:00', '2026-05-12 00:00:00', '2026-05-11 00:00:00',
 '2026-05-08 00:00:00', '2026-05-07 00:00:00', '2026-05-06 00:00:00',
 '2026-05-05 00:00:00', '2026-05-04 00:00:00', '2026-04-30 00:00:00',
 '2026-04-29 00:00:00',
 ...
 '2000-04-21 00:00:00', '2000-04-19 00:00:00', '2000-04-17 00:00:00',
 '2000-04-14 00:00:00', '2000-04-12 00:00:00', '2000-04-10 00:00:00',
 '2000-04-07 00:00:00', '2000-04-05 00:00:00', '2000-04-03 00:00:00',
 '2000-03-31 00:00:00']
Length: 3736, dtype: datetime64[us]

In [7]:
d=load_data()
d[d['symbole']=='ABJC']['date'].unique()

<StringArray>
['2026-05-13', '2026-05-12', '2026-05-11', '2026-05-08', '2026-05-07',
 '2026-05-06', '2026-05-05', '2026-05-04', '2026-04-30', '2026-04-29',
 '2026-04-28', '2026-04-27', '2026-04-24', '2026-04-23', '2026-04-22',
 '2026-04-21', '2026-04-20', '2026-04-17', '2026-04-16', '2026-04-15',
 '2026-04-14', '2026-04-13']
Length: 22, dtype: str

In [8]:
d.date.unique()

<StringArray>
['2026-05-13', '2026-05-12', '2026-05-11', '2026-05-08', '2026-05-07',
 '2026-05-06', '2026-05-05', '2026-05-04', '2026-04-30', '2026-04-29',
 '2026-04-28', '2026-04-27', '2026-04-24', '2026-04-23', '2026-04-22',
 '2026-04-21', '2026-04-20', '2026-04-17', '2026-04-16', '2026-04-15',
 '2026-04-14', '2026-04-13']
Length: 22, dtype: str

In [3]:
df_brvm1[df_brvm1['symbole']=='BOABF']

,symbole,nom,volume,previous_close,open,high,low,close,variation,valeur_echangee,per,pourcentage_valeur,date,SMA_20,SMA_50,RSI_14
5,BOABF,BANK OF AFRICA BURKINA FASO,2437,5410.0,5400,5405,5405,5405,-0.09,13169135,12.36,1.01,2026-05-14,5475.50,5391.6,50.485437
52,BOABF,BANK OF AFRICA BURKINA FASO,2437,5410.0,5400,5410,5405,5405,-0.09,13169135,12.36,1.01,2026-05-13,5486.75,5379.2,48.598131
99,BOABF,BANK OF AFRICA BURKINA FASO,5219,5410.0,5400,5410,5410,5410,0.00,28188865,12.36,1.92,2026-05-12,5498.75,5366.9,35.135135
146,BOABF,BANK OF AFRICA BURKINA FASO,3605,5400.0,5400,5435,5400,5410,0.19,19503050,12.36,1.16,2026-05-11,5512.25,5352.7,34.437086
193,BOABF,BANK OF AFRICA BURKINA FASO,1414,5400.0,5405,5435,5400,5400,0.00,7635600,12.34,0.66,2026-05-08,5525.75,5337.7,34.868421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124376,BOABF,BANK OF AFRICA BURKINA FASO,26921,737.0,745,745,745,745,1.09,20056145,1.70,8.63,2011-01-07,NaN,NaN,NaN
124397,BOABF,BANK OF AFRICA BURKINA FASO,32321,750.0,737,737,737,737,-1.73,23820577,1.68,25.09,2011-01-06,NaN,NaN,NaN
124412,BOABF,BANK OF AFRICA BURKINA FASO,97523,750.0,750,750,750,750,0.00,73142250,1.71,48.38,2011-01-05,NaN,NaN,NaN
124429,BOABF,BANK OF AFRICA BURKINA FASO,38641,714.0,750,750,750,750,5.04,28980750,1.71,12.97,2011-01-04,NaN,NaN,NaN
124444,BOABF,BANK OF AFRICA BURKINA FASO,11400,NaN,714,714,714,714,NaN,8139600,1.63,18.68,2011-01-03,NaN,NaN,NaN